### ISSUE TITLE
Working on a Docker Compose clustering example

### ISSUE THREAD

**Issue by sayden** [klaemo/docker-couchdb#102]
Hi, I have been working on an example with Docker Compose and a small modification in one of your images, I haven't upload it yet (I'll do it during the weekend) but maybe you can host it here with the rest.

In short, compose file sets a `NODENAME`, `COUCHDB_USER` and `COUCHDB_PASSWORD` for container.

```
version: '2'
services:
  coordinator:
    container_name: coordinator
    image: sayden/couchdb2:compose
    network_mode: docker_internal_net
    environment:
    - NODENAME=coordinator
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=password
    ports:
    - "5984:5984"
    - "5986:5986"
    - "6984:6984"
  worker1:
    container_name: worker1
    image: sayden/couchdb2:compose
    network_mode: docker_internal_net
    environment:
    - NODENAME=worker1
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=password
  worker2:
    container_name: worker2
    image: sayden/couchdb2:compose
    network_mode: docker_internal_net
    environment:
    - NODENAME=worker2
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=password
  worker3:
    container_name: worker3
    image: sayden/couchdb2:compose
    network_mode: docker_internal_net
    environment:
    - NODENAME=worker3
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=password
```

Also, `local.ini` needed a bit more of data to work. This is the resulting one:

```
[chttpd]
port = 5984
bind_address = 0.0.0.0

[httpd]
port = 5986
bind_address = 0.0.0.0
enable_cors = true
```

Finally I also expose `5986`

Tell me if you want it here and I'll make you a pull request.
