### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by maasencioh** [klaemo/docker-couchdb#108]
Hello, we're deploying several couchdb images with docker-compose, so we need them to be running with a different port to the default one, how can this be archived?

Currently I'm trying like this:
```yml
version: '2'
services:
  couchdb:
    image: klaemo/couchdb:2.0.0
    ports:
      - '3000:5984'

  user-crud:
    build: .
    environment:
      PORT: '3000'
      ROOT_URL: 'couchdb'
    ports:
      - '4000:4000'
    links:
      - couchdb
```
